apiVersion: batch/v1
kind: Job
metadata:
  name: terraform
spec:
  template:
    spec:
      containers:
      - name: terraform
        image: kaustubhkagrawal/codebit-terraform
        env:
        - name: TF_VAR_url
          value: "http://rabbitmq:15672"
        - name: TF_VAR_username
          value: "guest"
        - name: TF_VAR_password
          value: "guest"
        command: ["terraform",  "apply", "-auto-approve", "-state=/data/tfstate/terraform.tfstate"]
        volumeMounts:
        - mountPath: /data/tfstate
          name: terraform-volume
      volumes:
      - name: terraform-volume
        persistentVolumeClaim:
          claimName: myclaim
      restartPolicy: OnFailure
