apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.8.0-management-alpine
        name: rabbitmq
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-volume
        ports:
        - containerPort: 5672
      # volumes:
      # - name: rabbitmq-volume
      #   emptyDir: {}
      volumes:
      - name: rabbitmq-volume
        persistentVolumeClaim:
          claimName: myclaim
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    run: rabbitmq
status:
  loadBalancer: {}
